#include<stdio.h>
#include<string.h>
void main(void)                 //main函数 如果不是申明为void则默认为返回值为 int 型
{								//__  main() 这样的形式在函数结尾中要有一个 return 返回一个数。程序才不会出错

	int j=11;
	int i;
	char s[]="name";
	char d[]="hello";
	char st[3][19]={"tiantianxiangshang","haohaoxuexi","mengmengda"};

	printf("%s\n",st[0]);
	printf("%c\n",st[0][12]);     //不能是st[12]
	st[0][18]='2';                //将第一个字符串和第二个字符串连接起来。
	printf("%s\n",st[0]);

	for(i=0; i<8; i++,j++)
		st[1][j]='0';              //将三个字符串通过更改0结束标志来连接起来
	printf("%s\n",st[0]);

	printf("还有更好的办法哦！\n");
	strcat(d,s); 
	//strcat函数的使用，将第二条字符串第一个字符覆盖在第一条字符串0结束标志上，
	//strcat("qqqa","qazzx");错误的方法，不可以这样
	
	printf("%s\n",d);         //声明 char * strcat(char*, char*)函数返回第一个参数的值
	printf("%s\n",strcat(d,s));//char *_cedcl strcat (char * dst, char * src )

                               //{  char * cp=dst;      (保存指针)
	                           //   while(*cp)           
                               //        cp++;           （查找srt字符串的末尾）
                              //    while(*cp++ = *src);（拷贝src字符串到dst末尾）
	                          //     return(dst);        （返回dst字符串指针）
                             //  }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                             //  strcat函数接受两个字符串的指针，将第二个字符串的一份拷贝添加到第一个字符串
							//       的结尾，从而使第一个字符串成为一个新的字符串，第二个字符串不变                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
}
	



